// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrlGvqW7PpZAyyIBiOrQKvorW4cZwHaB0',
    appId: '1:756345693557:web:f8fc4b26503e6aedb65f3c',
    messagingSenderId: '756345693557',
    projectId: 'reddit-3aedf',
    authDomain: 'reddit-3aedf.firebaseapp.com',
    storageBucket: 'reddit-3aedf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvxDkbCjTBC_Le8hLjstRnhiiTmw8ltHg',
    appId: '1:756345693557:android:b60d021edb3abeeab65f3c',
    messagingSenderId: '756345693557',
    projectId: 'reddit-3aedf',
    storageBucket: 'reddit-3aedf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_k_FPVGjfxoufVh4uUmCBk_AiKIqvVgw',
    appId: '1:756345693557:ios:b5f64d60176c612fb65f3c',
    messagingSenderId: '756345693557',
    projectId: 'reddit-3aedf',
    storageBucket: 'reddit-3aedf.appspot.com',
    iosBundleId: 'com.example.reddit',
  );
}
